/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

SELECT * FROM [gold].[dim_customers]
SELECT * FROM [gold].[dim_products]
SELECT * FROM [gold].[fact_sales]

-- Find total customers by countries
SELECT 
    country ,
    COUNT(customer_id) AS Total_Customer
FROM [gold].[dim_customers]
GROUP BY country
ORDER BY COUNT(customer_id) DESC

-- Find total customers by gender
SELECT 
    gender ,
    COUNT(customer_id) AS Total_Customer
FROM [gold].[dim_customers]
GROUP BY gender
ORDER BY COUNT(customer_id) DESC

-- Find total products by category
SELECT
    category ,
    COUNT(product_id) AS Total_Product
FROM [gold].[dim_products]
GROUP BY category
ORDER BY COUNT(product_id) DESC

-- What is the average costs in each category?
SELECT
    category ,
    AVG(cost) AS Avg_Cost
FROM [gold].[dim_products]
GROUP BY category
ORDER BY AVG(cost) DESC

-- What is the total revenue generated for each category?
SELECT
    GDP.category ,
    SUM(GFS.sales_amount) AS Total_Revenue
FROM      [gold].[fact_sales] AS GFS 
LEFT JOIN [gold].[dim_products] AS GDP
ON GFS.product_key = GDP.product_key
GROUP BY GDP.category
ORDER BY SUM(GFS.sales_amount) DESC

-- What is the total revenue generated by each customer?
SELECT
    GDC.customer_id ,
    GDC.first_name ,
    GDC.last_name ,
    SUM(GFS.sales_amount) AS Total_Revenue
FROM [gold].[fact_sales] AS GFS 
LEFT JOIN [gold].[dim_customers] AS GDC
ON GFS.customer_key = GDC.customer_key
GROUP BY GDC.customer_id ,
         GDC.first_name ,
         GDC.last_name
ORDER BY SUM(GFS.sales_amount) DESC


-- What is the distribution of sold items across countries?
SELECT
    GDC.country ,
    SUM(quantity) AS Total_Quantitiy
FROM [gold].[fact_sales] AS GFS 
LEFT JOIN [gold].[dim_customers] AS GDC
ON GFS.customer_key = GDC.customer_key
GROUP BY GDC.country
ORDER BY SUM(quantity) DESC